<?xml version="1.0" encoding="utf-8"?>
<feature>
	<version>1</version>
	<uuid/>
	<name>Global Min/Max: Curvature Criteria</name>
	<type>13</type>
	<res_file_key>fa1cfecb-9ce6-485f-b344-3a4f87ac8f5e</res_file_key>
	<cs_name/>
	<cs_uuid/>
	<x_form>
		<global>true</global>
		<origin>
			<item>0</item>
			<item>0</item>
			<item>0</item>
		</origin>
		<translate>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
			<item>0</item>
			<item>0</item>
			<item>0</item>
			<item>1</item>
		</translate>
	</x_form>
	<display_bl>false</display_bl>
	<interpolate>true</interpolate>
	<use_cad_geom>false</use_cad_geom>
	<moving_reference>true</moving_reference>
	<moving_display>true</moving_display>
	<full_task>false</full_task>
	<use_in_BRP>false</use_in_BRP>
	<parameter>
		<uuid>75DFCDB4-7901-4E35-890C-36E27084CED8</uuid>
		<name>Curvature Criteria</name>
		<unit>2</unit>
		<formula/>
		<formula2/>
		<formula3/>
		<locality>0</locality>
	</parameter>
</feature>
